'use strict';

// ランディングページの言語別静的生成（scripts/build-landing.js）の回帰テスト。
//
// - index.html（日本語 / 既定 / x-default）と en/index.html（英語）がソースから再生成した
//   結果と一致すること（生成物のコミット漏れを検出）
// - 各ページの lang / title / description / canonical / hreflang / og:locale / 既定言語が
//   言語ごとに正しいこと。hreflang に ?lang= クエリを使わないこと
// - /en/ 配下の相対リンク・画像・フォントがすべて実在するファイルへ解決すること
// - JSON-LD の softwareVersion が package.json と同期していること
// - 日本語ページへの再適用が冪等であること

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { buildLandingPages, LANGUAGES, SITE_URL } = require('../scripts/build-landing.js');

const ROOT = path.resolve(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), 'utf8');
}

function attr(html, re, label) {
  const m = html.match(re);
  assert.ok(m, `${label} not found`);
  return m[1];
}

function main() {
  const built = buildLandingPages();
  const { outputs, translations } = built;

  // 1. 生成物がコミット済みファイルと一致する
  for (const [file, html] of Object.entries(outputs)) {
    assert.equal(read(file), html, `${file} is out of date — run \`npm run build\` and commit`);
  }
  assert.deepEqual(Object.keys(outputs).sort(), ['en/index.html', 'index.html']);

  // 2. 言語ごとのメタデータ
  for (const [language, config] of Object.entries(LANGUAGES)) {
    const html = outputs[config.file];
    const strings = translations[language];
    const pageUrl = SITE_URL + config.dir;

    assert.equal(attr(html, /<html lang="([^"]*)">/, 'html lang'), language, `${config.file}: lang`);
    assert.equal(attr(html, /<title>([^<]*)<\/title>/, 'title'), strings.metaTitle, `${config.file}: title`);
    assert.equal(attr(html, /<meta name="description"\s+content="([^"]*)"/, 'description'), strings.metaDescription);
    assert.equal(attr(html, /<meta property="og:locale" content="([^"]*)"/, 'og:locale'), config.locale);
    assert.equal(attr(html, /<meta property="og:url" content="([^"]*)"/, 'og:url'), pageUrl);
    assert.equal(attr(html, /<link rel="canonical"\s+href="([^"]*)"/, 'canonical'), pageUrl);
    assert.equal(attr(html, /<link rel="alternate" hreflang="ja"\s+href="([^"]*)"/, 'hreflang ja'), SITE_URL);
    assert.equal(attr(html, /<link rel="alternate" hreflang="en"\s+href="([^"]*)"/, 'hreflang en'), SITE_URL + 'en/');
    assert.equal(attr(html, /<link rel="alternate" hreflang="x-default"\s+href="([^"]*)"/, 'hreflang x-default'), SITE_URL);
    assert.ok(!/<link[^>]*hreflang[^>]*\?lang=/.test(html), `${config.file}: hreflang must not use ?lang=`);
    assert.equal(attr(html, /\n {4}let lang = "([^"]*)";\n/, 'let lang'), language, `${config.file}: default language`);
    assert.equal(attr(html, /"softwareVersion": "([^"]*)"/, 'softwareVersion'), pkg.version, `${config.file}: JSON-LD version`);
    assert.equal(attr(html, /"inLanguage": "([^"]*)"/, 'inLanguage'), language);

    // 言語ボタン: 現在の言語が active、移動先が設定されている
    for (const buttonLanguage of Object.keys(LANGUAGES)) {
      const re = new RegExp(`<button type="button" data-lang-button="${buttonLanguage}" data-lang-href="([^"]*)" aria-pressed="(true|false)"( class="active")?>`);
      const m = html.match(re);
      assert.ok(m, `${config.file}: lang button ${buttonLanguage}`);
      assert.equal(m[1], config.buttonHref[buttonLanguage]);
      assert.equal(m[2], String(buttonLanguage === language));
      assert.equal(Boolean(m[3]), buttonLanguage === language);
    }

    // 本文の代表箇所が辞書で静的に埋まっている
    assert.ok(html.includes(`data-i18n="heroEyebrow">${strings.heroEyebrow}<`), `${config.file}: heroEyebrow rendered`);
    assert.ok(html.includes(`data-i18n="navExamples">${strings.navExamples}<`), `${config.file}: navExamples rendered`);
  }

  // 3. /en/ の相対 URL がすべて実在ファイルへ解決する
  const en = outputs['en/index.html'];
  const enDir = path.join(ROOT, 'en');
  const urls = [];
  // 属性名の直前が空白のものだけ（data-lang-href="./" は言語ボタンの移動先なので対象外）
  for (const m of en.matchAll(/\s(?:href|src)="([^"]*)"/g)) urls.push(m[1]);
  for (const m of en.matchAll(/url\("([^"]*)"\)/g)) urls.push(m[1]);
  const local = urls.filter((u) => !/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(u));
  assert.ok(local.length > 20, 'expected many local references in en/index.html');
  for (const url of local) {
    assert.ok(url.startsWith('../'), `en/index.html: local url must be prefixed with ../: ${url}`);
    const clean = url.replace(/[?#].*$/, '');
    const target = path.resolve(enDir, clean);
    const exists = fs.existsSync(target) && (!clean.endsWith('/') || fs.statSync(target).isDirectory());
    assert.ok(exists, `en/index.html: missing target for ${url}`);
  }
  assert.match(en, /^<!doctype html>\n<!-- Generated by scripts\/build-landing\.js/i, 'en/index.html carries generated notice after doctype');

  // 4. 日本語ページは既定・自己参照。生成通知は付かない
  const ja = outputs['index.html'];
  assert.ok(!ja.includes('Generated by scripts/build-landing.js'), 'index.html has no generated notice (it is the source)');
  assert.ok(!/(?:href|src)="\.\.\//.test(ja), 'index.html must not contain ../ prefixed urls');

  // 5. 冪等性: 日本語ページを入力にしても同じ結果
  const again = buildLandingPages({ source: ja });
  assert.equal(again.outputs['index.html'], ja, 'ja rendering is idempotent');
  assert.equal(again.outputs['en/index.html'], en, 'en rendering from normalized source is stable');

  // 6. 辞書に無いキーが無い（両言語）
  for (const [language, keys] of Object.entries(built.missing)) {
    assert.deepEqual(keys, [], `translations.${language} lacks keys: ${keys.join(', ')}`);
  }

  console.log('landing-i18n: OK');
}

main();
