/* Auto-generated by generate-handlers — DO NOT EDIT */
import { insole } from '../proto/insole';

export abstract class GeneratedClient {
  protected abstract call(cmdName: string, requestData: Uint8Array): Promise<Uint8Array>;
  protected abstract streamReceive(cmdName: string, requestData: Uint8Array): Promise<Uint8Array[]>;
  protected abstract streamSend(
    cmdName: string,
    messages: Uint8Array[],
    finalCmdName: string,
  ): Promise<Uint8Array>;

  async echo({ message = '' }: { message?: string } = {}): Promise<insole.EchoResponse> {
    const req = insole.EchoRequest.create({ message });
    const respData = await this.call('echo', insole.EchoRequest.encode(req).finish());
    return insole.EchoResponse.decode(respData);
  }

  async setTime({ epochMs = 0 }: { epochMs?: number } = {}): Promise<insole.SetTimeResponse> {
    const req = insole.SetTimeRequest.create({ epochMs });
    const respData = await this.call('set_time', insole.SetTimeRequest.encode(req).finish());
    return insole.SetTimeResponse.decode(respData);
  }

  async getWindow({ startMs = 0 }: { startMs?: number } = {}): Promise<insole.GetWindowResponse> {
    const req = insole.GetWindowRequest.create({ startMs });
    const respData = await this.call('get_window', insole.GetWindowRequest.encode(req).finish());
    return insole.GetWindowResponse.decode(respData);
  }

  async setDeviceId({
    deviceId = 0,
  }: { deviceId?: number } = {}): Promise<insole.SetDeviceIdResponse> {
    const req = insole.SetDeviceIdRequest.create({ deviceId });
    const respData = await this.call('set_device_id', insole.SetDeviceIdRequest.encode(req).finish());
    return insole.SetDeviceIdResponse.decode(respData);
  }

  async setFoot({ foot = 0 }: { foot?: number } = {}): Promise<insole.SetFootResponse> {
    const req = insole.SetFootRequest.create({ foot });
    const respData = await this.call('set_foot', insole.SetFootRequest.encode(req).finish());
    return insole.SetFootResponse.decode(respData);
  }

  async getConfig(): Promise<insole.GetConfigResponse> {
    const req = insole.GetConfigRequest.create({});
    const respData = await this.call('get_config', insole.GetConfigRequest.encode(req).finish());
    return insole.GetConfigResponse.decode(respData);
  }

  async setLogUnit({
    timeUnitSec = 0,
    distanceUnitCode = 0,
  }: { timeUnitSec?: number; distanceUnitCode?: number } = {}): Promise<insole.SetLogUnitResponse> {
    const req = insole.SetLogUnitRequest.create({ timeUnitSec, distanceUnitCode });
    const respData = await this.call('set_log_unit', insole.SetLogUnitRequest.encode(req).finish());
    return insole.SetLogUnitResponse.decode(respData);
  }

  async otaBegin({ totalSize = 0 }: { totalSize?: number } = {}): Promise<insole.OtaBeginResponse> {
    const req = insole.OtaBeginRequest.create({ totalSize });
    const respData = await this.call('ota_begin', insole.OtaBeginRequest.encode(req).finish());
    return insole.OtaBeginResponse.decode(respData);
  }

  async otaWrite({
    offset = 0,
    data = new Uint8Array(0),
  }: { offset?: number; data?: Uint8Array } = {}): Promise<insole.OtaWriteResponse> {
    const req = insole.OtaWriteRequest.create({ offset, data });
    const respData = await this.call('ota_write', insole.OtaWriteRequest.encode(req).finish());
    return insole.OtaWriteResponse.decode(respData);
  }

  async otaApply(): Promise<insole.OtaApplyResponse> {
    const req = insole.OtaApplyRequest.create({});
    const respData = await this.call('ota_apply', insole.OtaApplyRequest.encode(req).finish());
    return insole.OtaApplyResponse.decode(respData);
  }

  async startMeasurement({
    activityId = 0,
  }: { activityId?: number } = {}): Promise<insole.StartMeasurementResponse> {
    const req = insole.StartMeasurementRequest.create({ activityId });
    const respData = await this.call('start_measurement', insole.StartMeasurementRequest.encode(req).finish());
    return insole.StartMeasurementResponse.decode(respData);
  }

  async stopMeasurement(): Promise<insole.StopMeasurementResponse> {
    const req = insole.StopMeasurementRequest.create({});
    const respData = await this.call('stop_measurement', insole.StopMeasurementRequest.encode(req).finish());
    return insole.StopMeasurementResponse.decode(respData);
  }

  async listLogs(): Promise<insole.ListLogsResponse> {
    const req = insole.ListLogsRequest.create({});
    const respData = await this.call('list_logs', insole.ListLogsRequest.encode(req).finish());
    return insole.ListLogsResponse.decode(respData);
  }

  async readLog({ index = 0 }: { index?: number } = {}): Promise<insole.ReadLogResponse> {
    const req = insole.ReadLogRequest.create({ index });
    const respData = await this.call('read_log', insole.ReadLogRequest.encode(req).finish());
    return insole.ReadLogResponse.decode(respData);
  }

  async eraseLogs(): Promise<insole.EraseLogsResponse> {
    const req = insole.EraseLogsRequest.create({});
    const respData = await this.call('erase_logs', insole.EraseLogsRequest.encode(req).finish());
    return insole.EraseLogsResponse.decode(respData);
  }

  async getGaitLive(): Promise<insole.GetGaitLiveResponse> {
    const req = insole.GetGaitLiveRequest.create({});
    const respData = await this.call('get_gait_live', insole.GetGaitLiveRequest.encode(req).finish());
    return insole.GetGaitLiveResponse.decode(respData);
  }

  async readChunk({ index = 0 }: { index?: number } = {}): Promise<insole.ReadChunkResponse> {
    const req = insole.ReadChunkRequest.create({ index });
    const respData = await this.call('read_chunk', insole.ReadChunkRequest.encode(req).finish());
    return insole.ReadChunkResponse.decode(respData);
  }

  async readEvent({ index = 0 }: { index?: number } = {}): Promise<insole.ReadEventResponse> {
    const req = insole.ReadEventRequest.create({ index });
    const respData = await this.call('read_event', insole.ReadEventRequest.encode(req).finish());
    return insole.ReadEventResponse.decode(respData);
  }

  async getFaultLog(): Promise<insole.GetFaultLogResponse> {
    const req = insole.GetFaultLogRequest.create({});
    const respData = await this.call('get_fault_log', insole.GetFaultLogRequest.encode(req).finish());
    return insole.GetFaultLogResponse.decode(respData);
  }
}
