#!/usr/bin/env node
'use strict';

/**
 * ランディングページの言語別静的生成
 *
 *   node scripts/build-landing.js          # index.html を正規化し en/index.html を生成
 *   node scripts/build-landing.js --check  # 生成結果とコミット済みファイルの差分を検査（CI 用、書き込みなし）
 *
 * ## 何をするか
 *
 * `index.html` はランディングページの唯一のソースであり、同時に日本語ページ（/）でもある。
 * ページ内の `translations`（en / ja 辞書）と `data-i18n*` 属性を読み取り、
 *
 *   1. `index.html` に **日本語** 辞書を静的に適用する（`<html lang="ja">`、title / description /
 *      og:* / canonical / hreflang / JSON-LD / 言語ボタンの状態）。この処理は冪等で、
 *      既に日本語化された index.html に再適用しても変化しない。
 *   2. 同じソースから **英語** 辞書を適用した `en/index.html` を生成する。相対パス
 *      （examples/… assets/… demo-app/ docs/ README.md、CSS の url()）は `../` を前置して
 *      /en/ 配下から正しく解決されるようにする。
 *
 * これにより検索エンジンは JavaScript を実行せずに各言語の内容・lang・canonical・hreflang を
 * 読める。`?lang=` クエリによる旧リンクは、ページ内 JS が対応する静的ページへ置き換える。
 *
 * ## 編集ルール
 *
 * - 文言は `index.html` 内の `translations` 辞書を編集する（マークアップ側の文字列は
 *   このスクリプトが辞書で上書きするため、辞書に無い変更は失われる）。
 * - `en/index.html` は生成物。直接編集しない。
 * - 編集後は `npm run build`（この生成を含む）を実行し、生成物もコミットする。CI は
 *   `--check` で差分を検査する。
 *
 * このモジュールは Node の `require()` からも使え、`buildLandingPages()` は書き込みせずに
 * 生成結果を返す（tests/landing-i18n.test.js が利用）。
 */

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const SOURCE_FILE = 'index.html';
const SITE_URL = 'https://orphe-oss.github.io/ORPHE-INSOLE.js/';

/** 言語ごとの配信設定。ja が既定（/ と x-default）。 */
const LANGUAGES = {
  ja: {
    file: 'index.html',
    dir: '',
    locale: 'ja_JP',
    alternateLocale: 'en_US',
    relativePrefix: '',
    buttonHref: { ja: './', en: 'en/' },
  },
  en: {
    file: 'en/index.html',
    dir: 'en/',
    locale: 'en_US',
    alternateLocale: 'ja_JP',
    relativePrefix: '../',
    buttonHref: { ja: '../', en: './' },
  },
};

const GENERATED_NOTICE = '<!-- Generated by scripts/build-landing.js from index.html. Do not edit directly; edit index.html and run `npm run build`. -->\n';

function escapeText(value) {
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeAttribute(value) {
  return escapeText(value).replace(/"/g, '&quot;');
}

/** index.html 内の `const translations = {...};` を評価して辞書を得る。 */
function extractTranslations(html) {
  const match = html.match(/\n {4}const translations = (\{[\s\S]*?\n {4}\});\n/);
  if (!match) throw new Error('translations object not found in ' + SOURCE_FILE);
  const translations = vm.runInNewContext('(' + match[1] + ')', {}, { timeout: 1000 });
  for (const language of Object.keys(LANGUAGES)) {
    if (!translations[language]) throw new Error(`translations.${language} is missing`);
    for (const key of ['metaTitle', 'metaDescription']) {
      if (typeof translations[language][key] !== 'string') {
        throw new Error(`translations.${language}.${key} must be a string`);
      }
    }
  }
  return translations;
}

/**
 * `<tag … attr="key" …>…</tag>` の内容を辞書値で置き換える。
 * 同名タグの入れ子は想定しない（検出したら例外）。辞書に無いキーは元の内容を残す。
 */
function replaceElementContents(html, attr, strings, render, missing) {
  const open = new RegExp(`<([a-zA-Z][\\w-]*)(\\s[^<>]*?\\s${attr}="([^"]+)"[^<>]*)>`, 'g');
  let out = '';
  let pos = 0;
  let m;
  while ((m = open.exec(html)) !== null) {
    const [tag, , key] = [m[1], m[2], m[3]];
    const openEnd = m.index + m[0].length;
    const closeTag = `</${tag}>`;
    const closeIdx = html.indexOf(closeTag, openEnd);
    if (closeIdx < 0) throw new Error(`no closing ${closeTag} for ${attr}="${key}"`);
    const inner = html.slice(openEnd, closeIdx);
    if (new RegExp(`<${tag}[\\s>]`).test(inner)) {
      throw new Error(`nested <${tag}> inside ${attr}="${key}" is not supported`);
    }
    const value = strings[key];
    if (value === undefined) missing.push(key);
    out += html.slice(pos, openEnd) + (value === undefined ? inner : render(value)) + closeTag;
    pos = closeIdx + closeTag.length;
    open.lastIndex = pos;
  }
  return out + html.slice(pos);
}

/** `data-i18n-aria-label="key"` を持つタグの aria-label 属性を辞書値にする。 */
function replaceAriaLabels(html, strings, missing) {
  return html.replace(/<([a-zA-Z][\w-]*)(\s[^<>]*?\sdata-i18n-aria-label="([^"]+)"[^<>]*)>/g, (whole, tag, attrs, key) => {
    const value = strings[key];
    if (value === undefined) {
      missing.push(key);
      return whole;
    }
    const escaped = escapeAttribute(value);
    const nextAttrs = /\saria-label="[^"]*"/.test(attrs)
      ? attrs.replace(/\saria-label="[^"]*"/, ` aria-label="${escaped}"`)
      : `${attrs} aria-label="${escaped}"`;
    return `<${tag}${nextAttrs}>`;
  });
}

function setMetaContent(html, selector, value) {
  const re = new RegExp(`(<meta ${selector}\\s+content=")([^"]*)(")`);
  if (!re.test(html)) throw new Error(`meta not found: ${selector}`);
  return html.replace(re, `$1${escapeAttribute(value)}$3`);
}

function setLinkHref(html, selector, href) {
  const re = new RegExp(`(<link ${selector}\\s+href=")([^"]*)(")`);
  if (!re.test(html)) throw new Error(`link not found: ${selector}`);
  return html.replace(re, `$1${href}$3`);
}

function replaceOnce(html, re, replacement, label) {
  if (!re.test(html)) throw new Error(`${label} not found`);
  return html.replace(re, replacement);
}

/** `/en/` 配下から解決できるよう、ドキュメント相対の URL に `../` を前置する。 */
function prefixRelativeUrls(html, prefix) {
  if (!prefix) return html;
  const isDocumentRelative = (url) => !/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#|\.\.\/|\.\/)/i.test(url);
  const rewrite = (url) => (isDocumentRelative(url) ? prefix + url : url);
  // 属性名の直前が空白のものだけを対象にする（data-lang-href などは対象外）
  return html
    .replace(/(\s)(href|src)="([^"]*)"/g, (whole, space, attr, url) => `${space}${attr}="${rewrite(url)}"`)
    .replace(/url\("([^"]*)"\)/g, (whole, url) => `url("${rewrite(url)}")`);
}

function renderLanguage(source, language, translations, version) {
  const config = LANGUAGES[language];
  const strings = translations[language];
  const missing = [];
  let html = source;

  // 冪等にするため、前回の生成通知を取り除いてから処理する
  html = html.replace(GENERATED_NOTICE, '');

  // <html lang>, <title>
  html = replaceOnce(html, /<html lang="[^"]*">/, `<html lang="${language}">`, '<html lang>');
  html = replaceOnce(html, /<title>[^<]*<\/title>/, `<title>${escapeText(strings.metaTitle)}</title>`, '<title>');

  // メタデータ
  html = setMetaContent(html, 'name="description"', strings.metaDescription);
  html = setMetaContent(html, 'property="og:title"', strings.metaTitle);
  html = setMetaContent(html, 'property="og:description"', strings.metaDescription);
  html = setMetaContent(html, 'property="og:url"', SITE_URL + config.dir);
  html = setMetaContent(html, 'property="og:locale"', config.locale);
  html = setMetaContent(html, 'property="og:locale:alternate"', config.alternateLocale);
  html = setMetaContent(html, 'name="twitter:title"', strings.metaTitle);
  html = setMetaContent(html, 'name="twitter:description"', strings.metaDescription);

  // canonical / hreflang（ja が既定 = x-default）
  html = setLinkHref(html, 'rel="canonical"', SITE_URL + config.dir);
  html = setLinkHref(html, 'rel="alternate" hreflang="ja"', SITE_URL + LANGUAGES.ja.dir);
  html = setLinkHref(html, 'rel="alternate" hreflang="en"', SITE_URL + LANGUAGES.en.dir);
  html = setLinkHref(html, 'rel="alternate" hreflang="x-default"', SITE_URL + LANGUAGES.ja.dir);

  // JSON-LD: url / inLanguage / softwareVersion（package.json と同期）
  html = replaceOnce(html, /("url": ")https:\/\/orphe-oss\.github\.io\/ORPHE-INSOLE\.js\/(?:en\/)?(",\n {4}"applicationCategory")/,
    `$1${SITE_URL}${config.dir}$2`, 'JSON-LD url');
  html = replaceOnce(html, /("softwareVersion": ")[^"]*(")/, `$1${version}$2`, 'JSON-LD softwareVersion');
  if (/"inLanguage": "[^"]*"/.test(html)) {
    html = html.replace(/"inLanguage": "[^"]*"/, `"inLanguage": "${language}"`);
  } else {
    html = replaceOnce(html, /(\n {4}"softwareVersion": "[^"]*",)/, `$1\n    "inLanguage": "${language}",`, 'JSON-LD softwareVersion line');
  }

  // 本文
  html = replaceElementContents(html, 'data-i18n', strings, escapeText, missing);
  html = replaceElementContents(html, 'data-i18n-html', strings, (value) => String(value), missing);
  html = replaceAriaLabels(html, strings, missing);

  // 言語ボタン: 状態と移動先
  html = html.replace(/<button[^<>]*\sdata-lang-button="(ja|en)"[^<>]*>/g, (whole, buttonLanguage) => {
    const active = buttonLanguage === language;
    return `<button type="button" data-lang-button="${buttonLanguage}" data-lang-href="${config.buttonHref[buttonLanguage]}" aria-pressed="${active}"${active ? ' class="active"' : ''}>`;
  });

  // ページ内 JS の既定言語
  html = replaceOnce(html, /\n {4}let lang = "(?:ja|en)";\n/, `\n    let lang = "${language}";\n`, 'let lang');

  // /en/ 配下向けの相対パス
  html = prefixRelativeUrls(html, config.relativePrefix);

  // 生成物には doctype 直後に通知コメントを置く（doctype より前に置くと一部のバリデータが警告する）
  if (config.dir) {
    html = replaceOnce(html, /^(<!doctype html>\n)/i, `$1${GENERATED_NOTICE}`, '<!doctype html>');
  }

  return { html, missing: Array.from(new Set(missing)) };
}

/**
 * 生成結果を返す（書き込みはしない）。
 * @returns {{ outputs: Record<string,string>, missing: Record<string,string[]>, version: string }}
 */
function buildLandingPages(options = {}) {
  const root = options.root || ROOT;
  const source = options.source !== undefined ? options.source : fs.readFileSync(path.join(root, SOURCE_FILE), 'utf8');
  const version = options.version || JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;
  const translations = extractTranslations(source);
  const outputs = {};
  const missing = {};
  for (const language of Object.keys(LANGUAGES)) {
    const result = renderLanguage(source, language, translations, version);
    outputs[LANGUAGES[language].file] = result.html;
    missing[language] = result.missing;
  }
  return { outputs, missing, version, translations };
}

function main(argv) {
  const check = argv.includes('--check');
  const { outputs, missing } = buildLandingPages();
  let changed = 0;
  for (const [file, html] of Object.entries(outputs)) {
    const target = path.join(ROOT, file);
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (current === html) continue;
    changed += 1;
    if (check) {
      console.error(`[build-landing] ${file} is out of date. Run \`npm run build\` and commit the result.`);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, html);
      console.log(`[build-landing] wrote ${file}`);
    }
  }
  for (const [language, keys] of Object.entries(missing)) {
    if (keys.length) console.warn(`[build-landing] translations.${language} lacks: ${keys.join(', ')}`);
  }
  if (check && changed) process.exit(1);
  if (!changed) console.log('[build-landing] up to date');
}

if (require.main === module) {
  main(process.argv.slice(2));
}

module.exports = { buildLandingPages, LANGUAGES, SITE_URL, SOURCE_FILE, GENERATED_NOTICE };
