#!/usr/bin/env node
'use strict';

/**
 * dist/orphe-insole.js の生成
 *
 *   node scripts/build-dist.js          # dist/orphe-insole.js を生成（内容が同じなら書き込まない）
 *   node scripts/build-dist.js --check  # 生成結果とコミット済みファイルの差分を検査（書き込みなし）
 *
 * 出力 = バナー + 同梱ライブラリ（src/vendor/*.js、ガード付き）+ src/ORPHE-INSOLE.js
 *
 * ## 同梱の方針
 *
 * 以前の dist は src/ORPHE-INSOLE.js の単純コピーで、SDK 読み込み時に ORPHE-CORE.js リポジトリの
 * jsDelivr URL から quaternion.js / float16.min.js を自動ロードしていた。別リポジトリのコードを
 * 実行時に取り込む構造を無くすため、quaternion.js を src/vendor/ に固定して dist に同梱する
 * （float16 は INSOLE では未使用なので同梱しない）。
 *
 * 同梱コードは次のガードで包む:
 *   - `typeof Quaternion === 'undefined'` のときだけ評価する。同一ページで ORPHE-CORE.js が先に
 *     quaternion.js を読み込んでいれば何もしない（グローバルを上書きしない）。
 *   - UMD の AMD / CommonJS 分岐（define / exports / module）をローカル変数で隠し、常にグローバル
 *     （globalThis）へ公開させる。Node の require() で dist を読み込んだときに module.exports を
 *     Quaternion で上書きしてしまうのを防ぐ。
 *
 * 圧縮版（dist/orphe-insole.min.js）は package.json の build スクリプトが、このファイルの出力に
 * terser を掛けて生成する。@license を含むコメントは terser が保持する。
 *
 * このモジュールは Node の require() からも使え、buildDist() は書き込みせずに文字列を返す
 * （tests/insole-dist-bundle.test.js が利用）。
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SOURCE_FILE = 'src/ORPHE-INSOLE.js';
const OUTPUT_FILE = 'dist/orphe-insole.js';

/** 同梱するライブラリ。順序どおりに連結される。 */
const VENDOR_FILES = [
  { file: 'src/vendor/quaternion.js', global: 'Quaternion' },
];

function readText(root, file) {
  return fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n');
}

function banner(version) {
  return [
    `/*! ORPHE-INSOLE.js v${version} — bundled build.`,
    ` *  Generated by scripts/build-dist.js from ${SOURCE_FILE} plus the vendored libraries listed in src/vendor/README.md.`,
    ` *  Do not edit this file; edit src/ and run \`npm run build\`. */`,
  ].join('\n');
}

/**
 * 同梱ライブラリを「既にグローバルが定義されていれば評価しない」ガードで包む。
 * @param {{file:string, global:string}} vendor
 * @param {string} code
 */
function wrapVendor(vendor, code) {
  return [
    `// ── vendored: ${vendor.file} ─────────────────────────────────────────────`,
    `// グローバル ${vendor.global} が未定義のときだけ評価する（同一ページで ORPHE-CORE.js が先に読み込んだ場合は上書きしない）。`,
    `if (typeof ${vendor.global} === 'undefined') {`,
    `  (function () {`,
    `    // UMD の AMD / CommonJS 分岐を無効化し、常にグローバル（this = globalThis）へ公開させる`,
    `    var define, exports, module;`,
    code.trimEnd(),
    `  }).call(typeof globalThis !== 'undefined' ? globalThis : this);`,
    `}`,
    `// ── end vendored: ${vendor.file} ─────────────────────────────────────────`,
    '',
  ].join('\n');
}

/**
 * dist/orphe-insole.js の内容を返す（書き込みはしない）。
 * @param {{root?:string, version?:string}} [options]
 */
function buildDist(options = {}) {
  const root = options.root || ROOT;
  const version = options.version || JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;
  const source = readText(root, SOURCE_FILE);
  if (/cdn\.jsdelivr\.net\/gh\/Orphe-OSS\/ORPHE-CORE\.js/.test(source)) {
    throw new Error(`${SOURCE_FILE} must not load code from the ORPHE-CORE.js repository at runtime`);
  }
  const vendors = VENDOR_FILES.map((v) => wrapVendor(v, readText(root, v.file)));
  return [banner(version), ...vendors, source].join('\n');
}

function main(argv) {
  const check = argv.includes('--check');
  const output = buildDist();
  const target = path.join(ROOT, OUTPUT_FILE);
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
  if (current === output) {
    console.log(`[build-dist] ${OUTPUT_FILE} up to date`);
    return;
  }
  if (check) {
    console.error(`[build-dist] ${OUTPUT_FILE} is out of date. Run \`npm run build\` and commit the result.`);
    process.exit(1);
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, output);
  console.log(`[build-dist] wrote ${OUTPUT_FILE} (${output.length} bytes)`);
}

if (require.main === module) {
  main(process.argv.slice(2));
}

module.exports = { buildDist, wrapVendor, VENDOR_FILES, SOURCE_FILE, OUTPUT_FILE };
